spring.application.name=healthcare-file-backend
server.port=8080

# datasource PostgreSQl
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/healthcare-file-backend
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false


# generate schema ddl to create tables
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

# database initialization with data.sql after hibernate
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

logging.level.org.springframework.boot.autoconfigure.sql.init=DEBUG
logging.level.org.springframework.jdbc.datasource.init.ScriptUtils=DEBUG

# added this to prevent random info in json that causes testing of functionalities to be confusing.//TODO: Remove this later.
spring.jackson.deserialization.fail-on-unknown-properties=true

jwt.secret=Such_A_Long_SecReT_098179394728934--!@%$%&*
jwt.expiration-ms=3600000
