spring.application.name=healthcare-file-backend
server.port=8080

spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/healthcare-file-backend
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

logging.level.org.springframework.security=INFO

spring.jackson.deserialization.fail-on-unknown-properties=true

jwt.secret=${JWT_SECRET:dev-secret-12345678901234567890123456789012}
jwt.expiration-ms=3600000